import React from 'react'

const Chat = () => {
  return(<main className='Chat'><p><b><span style={{color: 'red'}}>Stranger: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'blue'}}>You: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'red'}}>Stranger: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'blue'}}>You: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'red'}}>Stranger: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'blue'}}>You: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'red'}}>Stranger: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'blue'}}>You: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'red'}}>Stranger: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'blue'}}>You: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'red'}}>Stranger: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'blue'}}>You: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'red'}}>Stranger: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'blue'}}>You: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'red'}}>Stranger: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'blue'}}>You: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'red'}}>Stranger: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'blue'}}>You: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'red'}}>Stranger: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'blue'}}>You: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'red'}}>Stranger: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'blue'}}>You: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'red'}}>Stranger: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>

<p><b><span style={{color: 'blue'}}>You: </span></b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat saepe nam officiis deleniti, eum eos quam veniam quae. Exercitationem deserunt maxime ea qui, assumenda nam harum odio ullam quae sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, mollitia nobis impedit commodi totam dicta excepturi quod suscipit cupiditate obcaecati dolorem itaque dolorum hic autem, earum ipsam alias? Vero, natus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum inventore reprehenderit nulla ad ipsa itaque voluptate quidem porro, molestias necessitatibus labore dicta fuga ullam repellendus, neque accusantium quos blanditiis tempora.</p>





  
  </main>)
};

export default Chat;
